baseURL = "https://bojt.club/"
# languageCode = "en-us"
title = "Böjt Club"
# sectionPagesMenu = "main"

languageCode = "en"
DefaultContentLanguage = "en"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Ez itt a böjtölők klubja"
author = "Posta Galamb"
description = "Regisztrálj ha érdekel"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@alexbilz.com"

## Menu items

ContentLanguageInSubdir = true

[languages]
[languages.en]
contentDir = "content/en"
languageName = "EN"
weight = 1

[languages.hu]
contentDir = "content/hu"
languageName = "HU"
weight = 0


[menu]
[[languages.en.menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[languages.en.menu.main]]
  name = "Posts"
  weight = 2
  identifier = "posts"
  url = "/post/"

  [[languages.en.menu.main]]
  name = "About"
  weight = 3
  identifier = "about"
  url = "/about/"

  [[languages.en.menu.main]]
  name = "Contact"
  weight = 4
  identifier = "contact"
  url = "/contact/"
  
  [[languages.en.menu.main]]
  name = "Categories"
  weight = 6
  identifier = "categories"
  url = "/categories/"

  [[languages.en.menu.main]]
  name = "Tags"
  weight = 7
  identifier = "tags"
  url = "/tags/"

[[languages.hu.menu.main]]
  name = "Honlap"
  identifier = "home"
  weight = 1
  url = "/hu/"

  [[languages.hu.menu.main]]
  name = "Posta"
  weight = 2
  identifier = "posts"
  url = "/hu/post/"

  [[languages.hu.menu.main]]
  name = "Magunkról"
  weight = 3
  identifier = "about"
  url = "/hu/about/"

  [[languages.hu.menu.main]]
  name = "Kontakt"
  weight = 4
  identifier = "contact"
  url = "/hu/contact/"
  
  [[languages.hu.menu.main]]
  name = "Landol"
  weight = 5
  identifier = "landing"
  url = "/landing/"

[[languages.hu.menu.main]]
  name = "Kategoriák"
  weight = 6
  identifier = "categories"
  url = "/hu/categories/"

  [[languages.hu.menu.main]]
  name = "Cimkék"
  weight = 7
  identifier = "tags"
  url = "/hu/tags/"
